### PR TITLE
Expose the 'INSTANA_AGENT_HTTP_LISTEN' variable

### PR DESCRIPTION
**Pull request by mdonkers**
Makes it possible to let the Instana Agent listen on all network
interfaces. By default will only listen on eth0 / any Docker bridge
network.
In general value of "*" should be provided so the agent will listen on
all networking interfaces

### CODE REVIEW

**Comment by wiggzz** [comment]
Looks good. My only concern is continuing to add configuration parameters to the helm chart - does our documentation describe under what circumstances to use these parameters?

**Comment by mdonkers** [comment]
I believe all config parameters used are described in our docs. So at least for all parameters used thus far, it should be clear.

**Comment by wiggzz** [comment]
We need to include a default value for this unless we want to make it required - as it stand if I don't provide this I get:
```
Error: render error in "instana-agent/templates/daemonset.yaml": template: instana-agent/templates/daemonset.yaml:65:26: executing "instana-agent/templates/daemonset.yaml" at <.Values.instana.agen...>: can't evaluate field listen in type interface {}
```

**Comment by wiggzz** [comment]
Just added a fix for this by using `.httpListen` instead of `.http.listen`. We could also make the checking logic more complex but this seems more consistent with the proxy settings.

**Pull request merged**
